### ISSUE TITLE
requirement for utf8-string .. is 0.3.8 better 1 

### ISSUE THREAD

**Issue by andrewufrank** [HeinrichApfelmus/threepenny-gui#107]
currently in 0.6.0.1 there is a requirement for utf8-string == 0.3.8
this causes conflicts with other packages which use the newest  utf8-string (i.e. version 1)
threepenny gui compiles with utf8-string-1
i recommend to lift the requirement.

thank you for moving threepenny gui to base > 5 !
i compiled with ghc 7.8 and 7.10 -- works!
andrew

**Comment by HeinrichApfelmus** [comment]
Thanks for the report!

It turns out that the dependency on `utf8-string` can probably be dropped entirely. I'll wait for the Travis results and then upload a new version.
