### ISSUE TITLE
Please bring back loadFile and loadDirectory

### ISSUE THREAD

**Issue by duplode** [HeinrichApfelmus/threepenny-gui#110]
Hello again!

While preparing to update my project to 0.6 I realized I would miss `loadFile` and `loadDirectory`. I was unsure whether to pester you with this request, but then I chanced upon [this StackOverflow question](http://stackoverflow.com/a/30273324/2751851) :-) My use case is similar to the one in the question; however, I don't think there is a clean workaround for me, as I currently use a temporary directory in `/tmp` to store files generated by the program before the user saves them.

**Comment by HeinrichApfelmus** [comment]
Dear Daniel,

I finally got around to fixing this! :smile: As of commit 2083d63f824a95d81f8b7bd36aeaa600ae59d0c9 , both functions are back in. Does that work for you?

**Comment by duplode** [comment]
Hi Heinrich,

I did a quick test with it, and it works as well as it did back in 0.5. Thanks!
