### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by sindikat** [HeinrichApfelmus/threepenny-gui#112]
In https://github.com/HeinrichApfelmus/threepenny-gui/blob/master/src/Graphics/UI/Threepenny/Core.hs#L364 instead of `convenience` it says `convience` 2 times, which ends up in http://hackage.haskell.org/package/threepenny-gui-0.6.0.2/docs/Graphics-UI-Threepenny-Core.html#v:element too.

**Comment by HeinrichApfelmus** [comment]
Thanks for conviently pointing this out to me! :smirk:

**Comment by HeinrichApfelmus** [comment]
Fixed. Thanks!
