### ISSUE TITLE
Set encoding in default index file

### ISSUE THREAD

**Issue by Altai-man** [HeinrichApfelmus/threepenny-gui#116]
Current "index.html" file doesn't set any encoding and browser(I'm running threepenny-gui with firefox 38, but I believe other browsers should do the same thing) complaints in console. It will be good to add some encoding by default(for example, utf-8) to prevent it. It's only one line of code and I can send pull request if needed.

**Comment by HeinrichApfelmus** [comment]
Fixed in commit f264995061dc6a41c59e844e6ef33cf8afdd0ff9. Thanks!
