### ISSUE TITLE
Compile error with GHC 7.4 / base-4.6

### ISSUE THREAD

**Issue by hvr** [HeinrichApfelmus/threepenny-gui#120]
As you can see from https://hackage.haskell.org/package/base-4.8.1.0/docs/Control-Concurrent.html#v:forkFinally `forkFinally` requires `base>=4.6`, please update your `.cabal` file for future releases (assuming you don't want to restore support for GHC 7.4)

I'm going to edit the affected releases on Hackage

```
[11 of 28] Compiling Foreign.JavaScript.Server ( src/Foreign/JavaScript/Server.hs, dist/dist-sandbox-a93ac81e/build/Foreign/JavaScript/Server.o )

src/Foreign/JavaScript/Server.hs:93:15: Not in scope: `forkFinally'
xcabal: Error: some packages failed to install:
threepenny-gui-0.6.0.3 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by HeinrichApfelmus** [comment]
Fixed in commit 32ea4f6fc4291885b44faa0951ef46723197aebc. Thanks for reporting and editing the hackage files!
