### ISSUE TITLE
Version constraints too tight for `vector` and `aeson` in threepenny-gui 0.6.0.3

### ISSUE THREAD

**Issue by andrewufrank** [HeinrichApfelmus/threepenny-gui#121]
it has a constraint aeson <0.9 which seems not necessary but forces a version of aeson which is not the newest and therefore not the one which is prefered by other modules. the constraint can be lifted and threepreeny-gui still compiles (wih ghc 7.10); i cannot see any negative effects.
thank you!
andrew

**Comment by HeinrichApfelmus** [comment]
Fixed in commit 721c37c2d18215777c0ec36b3c950fe26507eae6 .

**Comment by andrewufrank** [comment]
thank you!
andrew


On 10/30/2015 06:55 PM, Heinrich Apfelmus wrote:
>
> Fixed in commit 721c37c 
> <https://github.com/HeinrichApfelmus/threepenny-gui/commit/721c37c2d18215777c0ec36b3c950fe26507eae6> 
> .
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/HeinrichApfelmus/threepenny-gui/issues/121#issuecomment-152601936>.
>

-- 
Prof. Dr. sc.techn. Dr. h.c. Andrew U. Frank
				 +43 1 58801 12710 direct
Geoinformation, TU Wien          +43 1 58801 12700 office
Gusshausstr. 27-29               +43 1 55801 12799 fax
1040 Wien Austria                +43 676 419 25 72 mobil
