### ISSUE TITLE
jQuery version

### ISSUE THREAD

**Issue by blitzcode** [HeinrichApfelmus/threepenny-gui#127]
From what I understand, the requested 'haskell.js' file will include the jquery bundled with threepenny. It seems to be a rather older version (1.7), which for instance the popular Bootstrap library lists as not in the compatible range. I imagine it would cause conflicts if I included another, newer jquery. I don't really know much about JS and if any of this will cause a problem, but maybe it would be possible to update the packaged jquery in threepenny?

**Comment by HeinrichApfelmus** [comment]
Err, sure. Is there a jQuery version you recommend?

**Comment by blitzcode** [comment]
I wouldn't know what a sensible choice here is, but I guess the most recent would be fine for most users?

**Comment by HeinrichApfelmus** [comment]
Solved in #136 , I think.
