### ISSUE TITLE
Escaping % in ffi call?

### ISSUE THREAD

**Issue by blitzcode** [HeinrichApfelmus/threepenny-gui#132]
Trying to call some client side JS through `ffi` with any %-sign in the string will fail, i.e.

    runFunction $ ffi "document.getElementById('content').innerHTML = \"<div style=\\\"width: 10%\\\"></div>\""

this will trigger the string substitution logic. It seems to silently fail, though. Took me a while to realize what the problem is. I might have missed something, but there's no way to escape a % in the string?

The only way I could make it work was by putting the entire string inside a parameter

    runFunction $ ffi "document.getElementById('content').innerHTML = %1" html

That does works and has the added benefit of doing all the quote escaping etc. automatically, but it would still be nice if there was a way to escape % in strings passed to `ffi`.

**Comment by HeinrichApfelmus** [comment]
Commit aa0d626e8d8289b7e66839785032527c83d2a36b should do the trick. Could you check that this works?

**Comment by blitzcode** [comment]
I can now include an escaped %-sign, nothing else seems to have broken either regarding ffi strings, thanks ;-)

**Comment by HeinrichApfelmus** [comment]
Sounds like it's time to close then. Thanks!
