### ISSUE TITLE
compile fails with 8.0.1 in 

### ISSUE THREAD

**Issue by andrewufrank** [HeinrichApfelmus/threepenny-gui#138]
cabal install threepenny-gui fails with the error msg:

`Compiling Foreign.RemotePtr ( src/Foreign/RemotePtr.hs, dist/build/Foreign/RemotePtr.o )

src/Foreign/RemotePtr.hs:37:25: error:
    • Couldn't match expected type ‘GHC.State# GHC.RealWorld
                                    -> (# GHC.State# GHC.RealWorld, c0 #)’
                  with actual type ‘IO ()’
    • In the third argument of ‘GHC.mkWeak#’, namely ‘f’
      In the expression: GHC.mkWeak# r# v f s
      In the expression:
        case GHC.mkWeak# r# v f s of {
          (# s1, w #) -> (# s1, GHC.Weak w #) }
`

this may be related to the change 
https://ghc.haskell.org/trac/ghc/ticket/5879

thank you for fixing!

**Comment by HeinrichApfelmus** [comment]
Thanks for reporting!

**Comment by andrewufrank** [comment]
thank you  - the version from git did compile. do you intend to upload
to hackage?
andrew

ps. i do not understand best practice for version numbers. the git
version is sitll 0.6.0.6, depsite your fix. when should a version
change? (honest question!)

-- 
Prof. Dr. sc.techn. Dr. h.c. Andrew U. Frank
                 +43 1 58801 12710 direct
Geoinformation, TU Wien          +43 1 58801 12700 office
Gusshausstr. 27-29               +43 1 55801 12799 fax
1040 Wien Austria                +43 676 419 25 72 mobil

**Comment by HeinrichApfelmus** [comment]
> do you intend to upload to hackage?

Some dependencies (`snap`) don't seem to work with GHC 8 yet. I will upload a new version of the library as soon as Travis testing reports success.

> the git version is still 0.6.0.6, despite your fix. when should a version change?

I have to admit that I am a bit lazy in this regard. I usually change the version when a release on Hackage is imminent.
