### ISSUE TITLE
Upper bounds prevent build with recent stackage nightly

### ISSUE THREAD

**Issue by blitzcode** [HeinrichApfelmus/threepenny-gui#139]
--  Failure when adding dependencies:
          data-default: needed (==0.5.*), 0.6.0 found (latest applicable is 0.5.3)
          template-haskell: needed (>=2.7.0 && <2.11), 2.11.0.0 found (latest applicable is 2.10.0.0)
    needed for package threepenny-gui-0.6.0.6

It would be great if threepenny could be added to Stackage to discover these version conflicts automatically. It's literally the only package I use that's not on Stackage and hence the only one that causes build issues when changing snapshots.

**Comment by HeinrichApfelmus** [comment]
I have bumped the dependencies.

Concerning compatibility with GHC 8.0.1, it appears that the Travis test fails because the `snap` package has not been updated yet.

**Comment by blitzcode** [comment]
Great! I also stumbled on some dependencies that don't build yet. There's quite a few things missing from the GHC8 Stackage nightlies, might take a while before everything is ported.

**Comment by HeinrichApfelmus** [comment]
I have bumped the dependencies and uploaded a maintenance release, version 0.7.0.0, to hackage. Everything should work on GHC 8.0 now as well.
