### ISSUE TITLE
NixOS build failing

### ISSUE THREAD

**Issue by remysucre** [HeinrichApfelmus/threepenny-gui#141]
`nix-env -iA haskellPackages.threepenny-gui` returns the following error: 

    src/Foreign/RemotePtr.hs:37:25: error:
        • Couldn't match expected type ‘GHC.State# GHC.RealWorld
                                        -> (# GHC.State# GHC.RealWorld, c0 #)’
                      with actual type ‘IO ()’
        • In the third argument of ‘GHC.mkWeak#’, namely ‘f’
          In the expression: GHC.mkWeak# r# v f s
          In the expression:
            case GHC.mkWeak# r# v f s of {
              (# s1, w #) -> (# s1, GHC.Weak w #) }
    builder for ‘/nix/store/vvxhzranpg6ssdsbhfgb3vp7599426nv-threepenny-gui-0.6.0.6.drv’ failed with exit code 1
    error: build of ‘/nix/store/vvxhzranpg6ssdsbhfgb3vp7599426nv-threepenny-gui-0.6.0.6.drv’ failed

I've pulled the most recent nixpkgs and have Haskell 8.0.1 installed. 
FYI Hydra also has [log](http://hydra.nixos.org/build/39156990/nixlog/1) of failing

**Comment by HeinrichApfelmus** [comment]
This particular issue has been fixed in commit 337c71aa75ea650abaff1d4d2b83cdc6b664b86c in the `master` branch, but the fix has not made its way to hackage yet. There are other dependencies that require an update; I will try to do that soon.

**Comment by remysucre** [comment]
Thanks! Closing.

**Comment by HeinrichApfelmus** [comment]
I have uploaded the current version, 0.7.0.0, to hackage. It works with the GHC 8 ecosystem.

**Comment by remysucre** [comment]
Thanks for the note!
