### ISSUE TITLE
Improve CI with stack and Appveyor

### ISSUE THREAD

**Issue by sjakobi** [HeinrichApfelmus/threepenny-gui#155]
* [x] A few stack-based Travis jobs could help insure that threepenny-gui stays compatible with old dependency versions.

* [x] Additional CI with Appveyor should be added to test that things work on Windows too.

* [x] We should also add a Travis job for macOS.

* [x] Add badges.

**Comment by sjakobi** [comment]
I have added a basic AppVeyor config now but [AppVeyor](https://ci.appveyor.com/project/sjakobi/threepenny-gui) doesn't seem to pick up changes in this repo so far.

I believe the issue is that I don't have admin permissions for this repo and therefore AppVeyor hasn't been able to add a webhook.

This can probably be fixed by @HeinrichApfelmus adding a webhook manually but I'm not sure what exactly that entails.

Alternatively @HeinrichApfelmus could open an AppVeyor account of his own (which is free) and enabling this project in that account. I believe this might be the easier way.

**Comment by HeinrichApfelmus** [comment]
> Alternatively @HeinrichApfelmus could open an AppVeyor account of his own (which is free) and enabling this project in that account. I believe this might be the easier way.

I have clicked on the necessary buttons and come [this far][1]. Does that help?

  [1]: https://ci.appveyor.com/project/HeinrichApfelmus/threepenny-gui

**Comment by sjakobi** [comment]
> I have clicked on the necessary buttons and come this far. Does that help?

Perfect! AppVeyor seems to pick up changes just as it should.

**Comment by sjakobi** [comment]
Completed with https://github.com/HeinrichApfelmus/threepenny-gui/commit/477fbb39e9f4a82b2ff9e581c7b07cc8f406ce22.
