### ISSUE TITLE
Simplified loading of static content

### ISSUE THREAD

**Issue by barischj** [HeinrichApfelmus/threepenny-gui#160]
To include a single CSS file we currently need to write a HTML file e.g. [/samples/static/chat.html](https://github.com/HeinrichApfelmus/threepenny-gui/blob/master/samples/static/chat.html) and serve the CSS file from our static folder. This is a lot of code for a single CSS file and also requires users to remember to include:
```Javascript
<script src="haskell.js"></script>
<script type="text/javascript" charset="utf-8">
    Haskell.initFFI();
</script>
```
(At least I'm not aware of a more simple way)

Suggestion is to add a way of importing CSS files that doesn't require so much wiring. Perhaps:
```Haskell
main = startGUI defaultConfig { includeCSS = ["/static/css/chat.css"] } setup
```

In the above case we edit the default served HTML by adding a stylesheet import pointing to "/static/css/chat.css".

Could also extend this mechanism for including scripts:
```Haskell
config = defaultConfig { includeScripts = [
    "/static/js/chat.js",
    "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"] }
main = startGUI config setup
```

**Comment by HeinrichApfelmus** [comment]
Well, for CSS stylesheets, there is the [addStyleSheet][1] function. Does that help?

  [1]: http://hackage.haskell.org/package/threepenny-gui-0.7.0.1/docs/Graphics-UI-Threepenny-Elements.html#v:addStyleSheet

**Comment by barischj** [comment]
Perfect, I dont know how I missed it.
