### ISSUE TITLE
Change dom asyncronously/with a delay? — Call buffering

### ISSUE THREAD

**Issue by Wizek** [HeinrichApfelmus/threepenny-gui#163]
As an example, I'd like a piece of text visible for some seconds, then change it to some other text.

I've tried two approaches:

```hs

import            Control.Concurrent.Async
import qualified  Graphics.UI.Threepenny        as UI
import            Graphics.UI.Threepenny.Core


testGui1 = startGUI defaultConfig $ \w -> do
  e <- UI.h1 # set UI.text "1"
  getBody w #+
    [ UI.span
    , element e
    ]
  liftIO $ threadDelay $ 1000 * 500
  element e # set UI.text "2"
  liftIO $ threadDelay $ 1000 * 500
  return ()

testGui2 = startGUI defaultConfig $ \w -> do
  e <- UI.h1 # set UI.text "1"
  getBody w #+
    [ UI.span
    , element e
    ]
  liftIO $ async $ runUI w $ do
    liftIO $ threadDelay $ 1000 * 500
    element e # set UI.text "2"
  return ()
```

- `testGui1` doesn't render "1" before showing "2".
- `testGui2` renders "1", then doesn't render "2".

Am I missing something here? Perhaps there is a third approach I haven't considered? Or is this a bug in threepenny-gui?

**Comment by HeinrichApfelmus** [comment]
Sorry for taking so long to reply.

The behavior you are seeing is due to "call buffering". See the note in the documentation for [runFunction][1]. I should probably mention it in the documentation more prominently.

  [1]: http://hackage.haskell.org/package/threepenny-gui-0.8.0.1/docs/Graphics-UI-Threepenny-Core.html#v:runFunction

**Comment by HeinrichApfelmus** [comment]
I have improved the documentation in commit c9a7077810fbe95ee2a4186afae9d24d0bc10ced . Feel free to reopen the issue if you feel that this is not good enough!
