### ISSUE TITLE
contextmenu

### ISSUE THREAD

**Issue by barischj** [HeinrichApfelmus/threepenny-gui#165]
I added some code in December relating to a contextmenu event and it's somehow not in release 0.7.0.1 which was uploaded February 1st.

See `Graphics.UI.Threepenny.Events.contextmenu`

**Comment by sjakobi** [comment]
v0.7.0.1 was only a maintenance release to restore compatibility with recent dependency versions. I'm sure  your code will be included in the next "feature release".

**Comment by barischj** [comment]
Wonderful thanking you
