### ISSUE TITLE
Application hangs on browser refresh

### ISSUE THREAD

**Issue by blitzcode** [HeinrichApfelmus/threepenny-gui#172]
I tried building my code with HEAD and noticed that on browser refresh my application hangs and consumes CPU time on both cores, needs to be killed with CTRL+C on the server-side, cleanup code doesn't run, not sure what's going on. Last know-good version was 4263658f026aac3db754663c3258ef8fb68cea1f and I think this bug has been introduced in either b256e6ea1b8c935db015917a26f228d4a05a801e or 121eb17e8386d0da58e96186d7dd1896d8a17e7e.

**Comment by HeinrichApfelmus** [comment]
I can reproduce that opening two separate browser windows and refreshing one of them will kill the other one. It appears that I have introduced this in commit 121eb17e8386d0da58e96186d7dd1896d8a17e7e .

**Comment by HeinrichApfelmus** [comment]
The fix was to add 16 characters of whitespace in the right place … 😮
