### ISSUE TITLE
loadFile in Canvas.hs

### ISSUE THREAD

**Issue by chisl** [HeinrichApfelmus/threepenny-gui#174]
> The functions loadFile and loadDirectory have been removed ...

as of v0.6.0.0 according to the changelog, but the sample file `Canvas.hs` still uses `loadFile`.

Strangely, the git-cloned threepenny-gui compiles ok, but in my own project the `loadFile` function is not found in `Graphics.UI.Threepenny`.

**Comment by duplode** [comment]
>Strangely, the git-cloned threepenny-gui compiles ok, but in my own project the `loadFile` function is not found in `Graphics.UI.Threepenny`.

That's because these functions were reintroduced a few commits ago. Cf. issue #110 .

**Comment by HeinrichApfelmus** [comment]
The functions are part of the 0.8 release, which I have just uploaded to hackage.
