### ISSUE TITLE
A web handler threw an exception

### ISSUE THREAD

**Issue by pepeiborra** [HeinrichApfelmus/threepenny-gui#183]
After upgrading to 0.8.0.0 I can no longer open my threepenny application. Instead, I get an HTTP 500 error code on my browser automatically requesting /favicon.ico

**Comment by HeinrichApfelmus** [comment]
Weird. Is the problem already present f4ac93e5d5d5ea1aa1f7a827d34a4f0f28f95e70 ? Does the server log say anything useful?

**Comment by pepeiborra** [comment]
Apologies, I cannot reproduce this anymore. Seems that my project might have been in an inconsistent state.

**Comment by HeinrichApfelmus** [comment]
No problem. 😄
