### ISSUE TITLE
State of  SVG.Attributes / camlcase

### ISSUE THREAD

**Issue by MarcFontaine** [HeinrichApfelmus/threepenny-gui#186]
The SVG.Attributes module contains many attributes that are defined in camlCase.
I ran in the situation that jquery automatically converts all uppercase letters in attributes to lower case
and that these  all-lower-case attributes then get ignored in svg elements since svg is case-sensitive.
Can anybody confirm that these attributes work at all (from Haskell) ?
What is the trick to get them to work (which browser/setup ) ?

**Comment by HeinrichApfelmus** [comment]
Hm, it appears that this is an issue with jQuery indeed ( jquery/jquery#2910 ). If I understand this correctly, it seems to be fixed in jQuery 3.* though, so the solution would be to upgrade the jQuery version bundled with threepenny-gui.

**Comment by HeinrichApfelmus** [comment]
Note to self: I'm looking into upgrading to jQuery 3.2.1, but it appears that Threepenny depends on jQuery 2.2.3 in a way that is not compatible with the newer version.

**Comment by HeinrichApfelmus** [comment]
I have upgraded the version of jQuery to 3.2.1 in commit 5ed387cc6f93b2752144b55133b489a628a4cd20 . This should fix the issue. Feel free to reopen if not!
