### ISSUE TITLE
Problems with session clean up?

### ISSUE THREAD

**Issue by fluffynukeit** [HeinrichApfelmus/threepenny-gui#19]
Let's keep this going!  I noticed an issue the other day and I am not sure how to diagnose it.  My TP worker starts out doing an IO action to read in a data file and build some Maps.  After this is complete and I'm ready to start using my GUI, my program uses around 110-120 MB of memory.  If I hit refresh in my browser, the memory in use goes to around 240-250 MB.  The increase in memory make sense to me - the map is being rebuilt just like the first time.  However, I don't understand why the old session's memory isn't cleaned up.  I let my program idle for 20 minutes to be sure there is plenty of time for cleanup timers and whatnot to run, but the memory never goes down.

I threw in some trace calls to try to figure it out but have had no luck so far.

**Comment by HeinrichApfelmus** [comment]
The code has changed so much, I have no idea whether this issue is still relevant. Closing.
