### ISSUE TITLE
absolute jsStatic path does not work

### ISSUE THREAD

**Issue by joeyh** [HeinrichApfelmus/threepenny-gui#194]
Setting jsStatic to an absolute path of Just "/usr/local/propellor/static", threepenny displayed exceptions like:

    static/egg.svg: getFileStatus: does not exist (No such file or directory)

I double-checked with strace, and and saw that indeed it's trying to open "static/egg.svg", rather than using the specified jsStatic directory.

threepenny-gui-0.8.0.0

**Comment by joeyh** [comment]
I had to use setWorkingDirectory to the directory that contains the "static" directory to work around this.

**Comment by HeinrichApfelmus** [comment]
Weird, at first I could reproduce this, but now I can't. Absolute paths seem to work fine for me, e.g.

    jsStatic = Just "/usr/share/doc/cups"

and visiting, say

  http://localhost:8023/static/robots.txt

Sorry, I can't reproduce this. Are you sure that the spelling of the path was correct?

**Comment by HeinrichApfelmus** [comment]
Please feel free to reopen if the issue persists!
