### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ndmitchell** [HeinrichApfelmus/threepenny-gui#197]
The current 0.8.1.0 release, as identified by the changelog, has useful enhancements - particularly #181. Any chance of making a release incorporating that?

**Comment by HeinrichApfelmus** [comment]
Working on it. I wanted to try to include [some low-hangig fruit][1], though.

  [1]: https://github.com/HeinrichApfelmus/threepenny-gui/projects/1

**Comment by ndmitchell** [comment]
Makes sense - looking forward to it.

**Comment by HeinrichApfelmus** [comment]
Thanks for the offer! For the 0.8.1.0 release, it's mostly a matter of finding time; most tasks are small, and I think it takes longer to describe them in sufficient detail than it takes to do them myself. 😄

**Comment by HeinrichApfelmus** [comment]
Here we go! http://hackage.haskell.org/package/threepenny-gui-0.8.1.0

**Comment by meteficha** [comment]
Awesome, thanks!
