### ISSUE TITLE
Trouble with garbage collection and Electron

### ISSUE THREAD

**Issue by bradrn** [HeinrichApfelmus/threepenny-gui#207]
I am building a library of bindings from threepenny-gui to electron. I was trying to create a context menu with the following code:
```Haskell
addContextMenu :: JSModule "electron" -> T.Menu -> UI ()
addContextMenu electron template = do               -- `electron` is a reference to the library generated via `require('electron')`
    menu <- buildFromTemplate electron template     -- returns a JSObject
    runFunction $ ffi "console.log(%1)" menu
    runFunction $ ffi "window.addEventListener('contextmenu', function (e) { e.preventDefault(); %2.popup(%1.remote.getCurrentWindow()) }, false);" electron menu
```
When I run electron, I can access and click on the context menu once, but the second time I try to access the context menu I get the following error:
```
Uncaught TypeError: Cannot read property 'popup' of undefined
    at eval (eval at receive (haskell.js:263), <anonymous>:1:152)
(anonymous) @ VM122:1
```
The mention of types and the fact that the `eval`'d code uses `StablePtr`s makes me think that this is a problem with threepenny-gui and not electron. The usage of `StablePtr`s also makes me think that something is being dereferenced after I use the context menu for the first time.

**Comment by HeinrichApfelmus** [comment]
This looks like the JavaScript object was garbage collected too early. What function did you use in `buildFromTemplate` to create the JSObject?

**Comment by bradrn** [comment]
> What function did you use in `buildFromTemplate` to create the JSObject?

It's a bit complicated. In the same order as the code:
- `T.MenuItem` is a large record corresponding to the electron [MenuItem](https://electron.atom.io/docs/api/menu-item/). `T.Menu` is a list of `T.MenuItem`s.
- `toTemplate :: T.MenuItem -> UI JSObject` creates JSObjects corresponding to the exported `click` handler and the submenu, then converts the `T.MenuItem` to a string and then a JSObject using `ffi`.
- `toTemplateMenu :: T.Menu -> UI JSObject` uses `toTemplate` to convert a `T.Menu` to a JSObject.
- Both `toTemplate` and `toTemplateMenu` use a function of type `[JSObject] -> UI JSObject`, implemented by exporting the `[JSObject]` to JavaScript and immediately importing it again as a `JSObject` (i.e. `callFunction . ffi "%1"`). This is a bit of a hack; there may be a better way.
- `Menu` (distinct from `T.Menu`!) is a `newtype` wrapper over `JSObject` for extra typesafety.
- Finally, `buildFromTemplate` calls `toTemplateMenu`, then calls the electron method `Menu.buildFromTemplate` (https://electron.atom.io/docs/api/menu/#menubuildfromtemplatetemplate), to get back a JSObject, which it then wraps in a `Menu`.

It may be worth noting that application menus also use `buildFromTemplate`, but only context menus have this problem, and even then only after a `click` event has been fired for one of the menu items.

**Comment by HeinrichApfelmus** [comment]
I see. This looks like a problem with garbage collection. The general rule is that any `JSObject` which has been garbage collected on the Haskell side cannot be re-obtained from an FFI call to the JavaScript side.

For instance, you first create several `JSObject` with `toTemplate`. Then, you combine them into a different `JSObject` by going through the JavaScript side. However, from the Haskell point of view, the new `JSObject` no longer "contains" the previous `JSObject`s — for all that GHC knows, the new `JSObject` could be some completely unrelated object. Hence, the previous `JSObject`s are garbage on the Haskell side and collected in due time.

The easiest way to fix this is to probably keep a reference to the previous objects in the `Menu` time. Alternatively, you can utilize the `Foreign.RemotePtr` module to make explicit references from the new `JSObject` to the previous ones.

If you work from the source version of Threepenny, you can use the `-DREBUG` flag to make garbage collection occur more often, highlighting problems much earlier.

----

Hm, though looking at your code, I'm not entirely sure anymore. Did you inspect the contents of `ffi "console.log(%1)"` in the browser? If the resulting object does not have a `popup` property, then things went wrong in `buildFromTemplate` already, otherwise something weird is going on.

**Comment by bradrn** [comment]
> The easiest way to fix this is to probably keep a reference to the previous objects in the `Menu` time.

Would '`Menu` time' be a typo for `MenuItem`? I don't think this would work, as the `MenuItem`s are only used by the user to provide a specification for a menu as follows:
```haskell
    addContextMenu electron [ mkMenuItem { T.label = Just "MenuItem1"
                                         , T.click = Just xItem1Clicked
                                         }
                            , mkMenuItem { T.label = Just "MenuItem2"
                                         , T.type_ = Just Checkbox
                                         , T.checked = Just True
                                         }
                            ...
```
I couldn't keep it in the `Menu` type either, as it is a thin newtype wrapper around a `JSObject`, and is used only as an intermediate step in the creation of a menu. In fact, I can remove it and it doesn't change the operation of the program in any way.

> Alternatively, you can utilize the `Foreign.RemotePtr` module to make explicit references from the new `JSObject` to the previous ones.

This sounds like it could work. How would I go about this?

> If you work from the source version of Threepenny, you can use the `-DREBUG` flag to make garbage collection occur more often, highlighting problems much earlier.

I'm not working from source, but using stack I can enable the flag using `stack build --flag threepenny-gui:-DREBUG`. It doesn't do anything.

> Did you inspect the contents of ffi "console.log(%1)" in the browser? If the resulting object does not have a popup property, then things went wrong in buildFromTemplate already, otherwise something weird is going on.

Here's the object:
![image](https://user-images.githubusercontent.com/17613703/32403389-592540f0-c18c-11e7-86fe-61ca077b050f.png)

---

Something I discovered just now: if I wait about 30 seconds before I try to use the context menu, it gives the error (`Uncaught TypeError` etc.) immediately and the context menu does not pop up. However, if I use the context menu immediately after the program starts, it pops up and I can click on the buttons. When a button is clicked, it works, but gives these errors:
![image](https://user-images.githubusercontent.com/17613703/32403538-afc5bf30-c190-11e7-8272-15846de55dee.png)
(Sorry the image is a bit small, you should be able to click on it to enlarge it)
When I try to use the context menu a second time, it starts giving errors again.

**Comment by HeinrichApfelmus** [comment]
>> Did you inspect the contents of ffi "console.log(%1)" in the browser? If the resulting object does not have a popup property, then things went wrong in buildFromTemplate already, otherwise something weird is going on.
>
> Here's the object: [..]

Hang on, then it should be impossible for `%1.popup` to fail. It appears to me that in your second line of code, you have accidentally interchanged `%1` and `%2`?

>> Alternatively, you can utilize the Foreign.RemotePtr module to make explicit references from the new JSObject to the previous ones.
>
> This sounds like it could work. How would I go about this?

The function `Foreign.RemotePtr.addReachable` makes one `JSObject` reachable from another one. An Haskell value can only be garbage collected if it is not reachable from a root object.

> Something I discovered just now: if I wait about 30 seconds before I try to use the context menu, it gives the error (Uncaught TypeError etc.) immediately and the context menu does not pop up. 

Again, all signs of something being garbage collected too early.

I'm not sure if I can help you much further without going into details. If you create a minimal working example that highlights the issue, I might be able to investigate in more detail.

**Comment by bradrn** [comment]
> Hang on, then it should be impossible for `%1.popup` to fail. It appears to me that in your second line of code, you have accidentally interchanged `%1` and `%2`?

No, I haven't interchanged them.

> If you create a minimal working example that highlights the issue, I might be able to investigate in more detail.

Here's a quasi-minimal example with almost identical behaviour:

```haskell
module Main where

import System.Environment (getArgs)
import System.IO

import qualified Graphics.UI.Threepenny       as UI
import           Graphics.UI.Threepenny.Core
import           Foreign.JavaScript           (JSObject)

main :: IO ()
main = do
    hSetBuffering stdout LineBuffering
    [port] <- getArgs
    startGUI defaultConfig {jsPort = Just $ read port} setup

setup :: Window -> UI ()
setup window = do
    electron <- callFunction $ ffi "require('electron')" :: UI JSObject
    clickFun <- ffiExport $ runUI window $ runFunction $ ffi "alert('I have been clicked')"
    menu <- callFunction $ ffi "[{label:'Click me',click:%1}]" clickFun :: UI JSObject
    menu' <- callFunction $ ffi "%1.remote.Menu.buildFromTemplate(%2)" electron menu :: UI JSObject
    runFunction $ ffi "window.addEventListener('contextmenu', function (e) { e.preventDefault(); %1.popup(%2.remote.getCurrentWindow()); }, false)" menu' electron
    return ()
```
If you run this in Electron, it produces almost exactly the same behaviour, except for one caveat: I can click the button more than once (usually four times) before it is garbage collected. Adding a `liftIO $ addReachable menu' menu` has no effect.

> The function `Foreign.RemotePtr.addReachable` makes one `JSObject` reachable from another one. A Haskell value can only be garbage collected if it is not reachable from a root value.

This doesn't seem to make any difference. It may help if I include the problematic code (`addReachable`s included):
```haskell
toTemplate :: T.MenuItem -> UI JSObject

toTemplateMenu :: T.Menu -> UI JSObject
toTemplateMenu = combine <=< sequence . fmap toTemplate

combine :: [JSObject] -> UI JSObject
combine os = do
    o <- callFunction $ ffi "%1" os
    liftIO $ traverse (addReachable o) os
    return o

newtype Menu = Menu { fromMenu :: JSObject } deriving (FromJS, ToJS)

buildFromTemplate :: JSModule "electron" -> T.Menu -> UI Menu
buildFromTemplate electron template = do
    menu <- toTemplateMenu template
    obj <- callFunction $ ffi "%1.remote.Menu.buildFromTemplate(%2)" electron menu
    liftIO $ addReachable obj menu
    return $ Menu obj

addContextMenu :: JSModule "electron" -> T.Menu -> UI ()
addContextMenu electron template = do
    menu <- buildFromTemplate electron template
    runFunction $ ffi "console.log(%1)" menu
    runFunction $ ffi "window.addEventListener('contextmenu', function (e) { e.preventDefault(); %2.popup(%1.remote.getCurrentWindow()) }, false);" electron menu
```
Am I missing something here?

**Comment by bradrn** [comment]
> Every browser window has a root pointer that is alive as long as the browser window is alive. It's `Foreign.JavaScript.root`. You have to attach both `electron` and `menu` to this root in some way, for instance by directly using them `addReachable`. (Alternatively, attach `electron` to the root, and `menu` to `electron`, building a tree.)

This worked in the minimal example:
```haskell
module Main where

import System.Environment (getArgs)
import System.IO

import qualified Graphics.UI.Threepenny       as UI
import           Graphics.UI.Threepenny.Core
import           Foreign.JavaScript           (JSObject, root)
import           Foreign.RemotePtr            (addReachable)

main :: IO ()
main = do
    hSetBuffering stdout LineBuffering
    [port] <- getArgs
    startGUI defaultConfig {jsPort = Just $ read port} setup

setup :: Window -> UI ()
setup window = do
    rootObj <- liftJSWindow $ return . root
    electron <- callFunction $ ffi "require('electron')" :: UI JSObject
    liftIO $ addReachable rootObj electron
    clickFun <- ffiExport $ runUI window $ runFunction $ ffi "alert('I have been clicked')"
    menu <- callFunction $ ffi "[{label:'Click me',click:%1}]" clickFun :: UI JSObject
    menu' <- callFunction $ ffi "%1.remote.Menu.buildFromTemplate(%2)" electron menu :: UI JSObject
    liftIO $ addReachable electron menu'
    runFunction $ ffi "window.addEventListener('contextmenu', function (e) { e.preventDefault(); %1.popup(%2.remote.getCurrentWindow()); }, false)" menu' electron
    return ()
```

Now I'll try to apply this to the larger application.

**Comment by bradrn** [comment]
I can't get it to work with the larger application. I've tried adding `addReachable`s and debugging it but I can't figure out what's being garbage collected. I would post my code but unfortunately it's a bit large - would you mind if I attached my code as a zip file for you to have a look at?

**Comment by HeinrichApfelmus** [comment]
Sure, you can do that, or make a Github repository. That said, I unfortunately, won't have time to look at it in the next couple of weeks.

**Comment by bradrn** [comment]
Here's the zip: [threepenny-electron-menu-bug.zip](https://github.com/HeinrichApfelmus/threepenny-gui/files/1469909/threepenny-electron-menu-bug.zip). The library (containing all the logic) is in the `electron-threepenny-lib` directory and the application is in the `menus` directory. To run the application, `cd` into `menus` and run:
```
$ npm install
$ stack install --local-bin-path bin
$ ./node_modules/.bin/electron electron.js
```

**Comment by bradrn** [comment]
Since I've _long_ stopped working with Electron, and this issue hasn't had any comments for about 2 years now, I'm closing this issue. Will re-open if I run into it again.
