### ISSUE TITLE
How to get a list of files from directory with threepenny-gui?

### ISSUE THREAD

**Issue by GilmarCorreia** [HeinrichApfelmus/threepenny-gui#247]
Hello threepenny-gui team.

I'm trying to make a Software with threepenny-gui and I'm facing some challenges, especially to get the files inside a directory in my computer with UI, like getDirectoryContents from System.Directory. 

If someone has a suggestion I would be thankful for your collaboration.

Greeting,

**Comment by bradrn** [comment]
Exactly which problems are you encountering? From what I can tell, this sounds like an issue with something in your program rather than with `threepenny-gui` itself.

**Comment by GilmarCorreia** [comment]
I have solved the problem, it was just managing the Monads.
