### ISSUE TITLE
Won't compile on Windows

### ISSUE THREAD

**Issue by liamzee** [HeinrichApfelmus/threepenny-gui#273]
Seems that something is wrong with the current Snap dependency:

![image](https://user-images.githubusercontent.com/104887453/208409552-8c56d7cf-b5fa-4816-9dea-421560a7f773.png)

**Comment by sjakobi** [comment]
I can't reproduce this on Linux. Does adding a `--constraint 'time < 1.10'` work?

In any case, this belongs at https://github.com/snapframework/snap-core/issues instead of this issue tracker.
