### ISSUE TITLE
The `getElementsBy..` functions do not work with a custom HTML file

### ISSUE THREAD

**Issue by jaccokrijnen** [HeinrichApfelmus/threepenny-gui#60]
`getElementsByClassName` is giving me problems. When calling it, I get the following error:

    user error (Pattern match failure in do expression at Graphics/UI/Threepenny/Core.hs:143:5-15)

To reproduce:
* add to `<body>` in wwwroot/chat.html:

        <div class="test">  
        </div>

* replace in `setup` src/Chat.hs:

        getBody window #+

  by

        first <- head <$> getElementsByClassName window "test"
        element first #+

**Comment by HeinrichApfelmus** [comment]
The aforementioned commit will be part of the 0.6 release.
